[build]

command = "npm run production"
publish = "build_production"
environment = { PHP_VERSION = "8.1" }

# SEO redirect
[[redirects]]
from = "https://alexanderpowell.netlify.com/*"
to = "https://www.alexanderpowell.me/:splat"
status = 301
